


keywords = {
    "duvet": "bedding",
    "towel": "textiles",
    "suitcase": "luggage",
    "light": "lighting",
    "throw": "textiles",
}

maps = [
        { "keyword": "duvet", "category": "bedding"},
        { "keyword": "pillow", "category": "bedding"},
        { "keyword": "sheet", "category": "bedding"},
        { "keyword": "bedding", "category": "bedding"},
        { "keyword": "mattress", "category": "bedding"},
        { "keyword": "towel", "category": "textiles"},
        { "keyword": "throw", "category": "textiles"},
        { "keyword": "suitcase", "category": "luggage"},
        { "keyword": "light", "category": "lighting"},
        { "keyword": "lamp", "category": "lighting"},
        { "keyword": "chandelier", "category": "lighting"},
        { "keyword": "fridge", "category": "kitchen"},
        { "keyword": "roast", "category": "kitchen"},
        { "keyword": "meat thermometer", "category": "kitchen"},
        { "keyword": "carving", "category": "kitchen"},
        { "keyword": "ricer", "category": "kitchen"},
        { "keyword": "saucepan", "category": "kitchen"},
        { "keyword": "frying pan", "category": "kitchen"},
        { "keyword": "casserole", "category": "kitchen"},
        { "keyword": "gravy boat", "category": "tableware"},
        { "keyword": "platter", "category": "tableware"},
        { "keyword": "dinner set", "category": "tableware"},
        { "keyword": "placemat", "category": "tableware"},
        { "keyword": "table runner", "category": "tableware"},
        { "keyword": "tablecloth", "category": "tableware"},
        { "keyword": "jigsaw puzzle", "category": "games"},
        { "keyword": "pedestal mat", "category": "bathroom"},
        { "keyword": "bath mat", "category": "bathroom"},
        { "keyword": "rug", "category": "rugs"},
        { "keyword": "curtain", "category": "curtains"},
        { "keyword": "cushion", "category": "cushions"},
        { "keyword": "christmas", "category": "christmas"},
        { "keyword": "advent", "category": "christmas"},
        { "keyword": "stocking", "category": "christmas"},
        { "keyword": "wreath", "category": "christmas"},
        { "keyword": "game", "category": "games"},
        { "keyword": "bbq", "category": "garden"}
]

names = [
  "Goose Feather & Down 10.5 Tog Duvet",
  "Set of 3 Carbon Steel Roasting Trays",
  "12 Piece Platinum Rim StayNew™ Dinner Set",
  "Cosy & Light Mattress Protector",
  "Carbon Steel Non-Stick Roast & Rack",
  "Cosy & Light 10.5 Tog Duvet",
  "Set of 5 Printed Tea Towels",
  "Pure Cotton Repeat Diamond Towel",
  "2 Pack Cosy & Light Medium Pillows",
  "Pure Cotton Repeat Diamond Towel",
  "Large Carving Board",
  "Cosy & Light 15 Tog Duvet",
  "Aluminium 40cm Large Non-Stick Roaster",
  "Goose Feather & Down Mattress Topper",
  "Set of 5 Printed Tea Towels",
  "Temperature Comfort Pillow Protector",
  "Porcelain StayNew™ Gravy Boat",
  "Goose Feather & Down 4.5 Tog Duvet",
  "Stainless Steel Meat Thermometer",
  "Temperature Comfort 4.5 Tog Duvet",
  "Jasper Set of 3 Soft Suitcases",
  "Pure Cotton Repeat Diamond Towel",
  "Cosy & Light 4.5 Tog Duvet",
  "Set of 3 Lisbon Hard Shell 8 Wheel Suitcase",
  "Percale 300 Thread Count Deep Fitted Sheet",
  "Percale 300 Thread Count Duvet Cover",
  "Pure Cotton Luxury Spa Towel",
  "Percale 300 Thread Count Fitted Sheet",
  "Percale 300 Thread Count Pillowcase",
  "Temperature Comfort Mattress Protector",
  "Percale 300 Thread Count Fitted Sheet",
  "Cosy & Light 13.5 Tog Duvet",
  "Two Tone 4 Wheel Soft Medium Suitcase",
  "Two Tone 4 Wheel Cabin Suitcase",
  "Ultralite 4 Wheel Soft Medium Suitcase",
  "Large Oval Platter",
  "Ultralite 4 Wheel Soft Cabin Suitcase",
  "Ultralite 4 Wheel Soft Large Suitcase",
  "Medium Oval Platter",
  "Scorpio 4 Wheel Hard Shell Cabin Suitcase",
  "Scorpio 4 Wheel Hard Shell Medium Suitcase",
  "Heritage 8 Wheel Hard Shell Medium Suitcase",
  "Set of 48 Glass Christmas Baubles",
  "2-in-1 Disney™ Classics Jigsaw Puzzle",
  "Porto 4 Wheel Hard Shell Large Suitcase",
  "Set of 4 Round Woven Placemats",
  "BBQ Wire Brush",
  "BBQ Spatula",
  "Erin Table Lamp",
  "Chenille Geometric Eyelet Curtains",
  "Pure Cotton Printed Bedding Set",
  "Linear Shine Rug",
  "Festive Soap Trio Gift Set",
  "Star Pencil Pleat Blackout Kids Curtains",
  "Patterned Glass Pendant Light",
  "Renzo Wool Rug",
  "Pure Cotton Ribbed Bath Mat",
  "Set of 4 Round Woven Placemats",
  "Bobble Rug",
  "Set of 2 Pure Cotton Striped Beach Towels",
  "Set of 2 Pure Cotton Striped Beach Towels",
  "Gem Ball Ceiling Light",
  "Pure Cotton Christmas Print Runner",
  "Pure Cotton Striped Pedestal Mat",
  "Bath Jelly Trio",
  "Cotton Ribbed Table Runner",
  "Large Cast Aluminum Roaster",
  "Simple Shade Pendant Light",
  "Leda Task Floor Lamp",
  "Pure Cotton Zig Zag Pedestal Mat",
  "Pure Cotton Foliage Embroidered Cushion",
  "Minimalistic Pendant Light",
  "Minimalistic Pendant Light",
  "Droplet Chandelier",
  "Cotton Mix Tree Bedding Set",
  "Patterned Glass Cluster Pendant Light",
  "Jacquard Cushion",
  "Butterfly Tassel Cushion",
  "Pure Cotton Knitted Throw",
  "Alexa Tripod Floor Lamp",
  "Egyptian Cotton Luxury Pedestal Mat",
  "Pure Cotton Striped Seersucker Bedding Set",
  "Linda Floral Curtains",
  "Ceramic 32cm Medium Roaster",
  "Cotton Mix Mushroom Bedding Set",
  "Chenille Triangle Eyelet Curtains",
  "Brushed Cotton Tree Bedding Set",
  "Alphabet Christmas Stocking",
  "Cotton Mix Butterfly Bedding Set",
  "Percale Deep Fitted Sheet",
  "Cotton Mix Geometric Bedding Set",
  "Percale Fitted Sheet",
  "Cotton Mix Ditsy Floral Bedding Set",
  "Percale Flat Sheet",
  "Percale Duvet Cover",
  "Pure Cotton Striped Seersucker Bedding Set",
  "Alexa Table Lamp",
  "Striped Chenille Cushion",
  "Tri Ply Textured Roaster",
  "Scorpio 4 Wheel Hard Shell Cabin Suitcase",
  "Henley Pure Wool Rug",
  "Egyptian Cotton Luxury Pedestal Mat",
  "Brushed Cotton Striped Bedding Set",
  "Cotton Tartan Tablecloth",
  "Cotton Mix Geometric Bedding Set with Fitted Sheet",
  "Faux Silk Pencil Pleat Blackout Curtains",
  "Cotton Bamboo Pedestal Mat",
  "Pure Cotton Forest Bedding Set",
  "Pure Cotton Zig Zag Pedestal Mat",
  "Large Cast Aluminum Roaster",
  "Palm Print Cushion",
  "Brushed Cotton Polar Bear Bedding Set",
  "Faux Fur Luxury Throw",
  "Faux Silk Pencil Pleat Blackout Curtains",
  "16 inch Lit Winterberry Wreath",
  "Linear Shine Rug",
  "Bobble Striped Pedestal Mat",
  "Geometric Chenille Cushion",
  "Large Cast Aluminum Roaster",
  "Velvet Robin Small Embroidered Cushion",
  "Thermal Pencil Pleat Blackout Curtains",
  "Large Potato Ricer",
  "Jacquard Cushion",
  "Geometric Chenille Cushion",
  "Set of 3 Assorted Kitchen Towels",
  "Geometric Chenille Cushion",
  "Palm Print Cushion",
  "Set of 3 Assorted Kitchen Towels",
  "Large Cast Aluminum Roaster",
  "Large Cast Aluminum Roaster",
  "Herringbone Throw",
  "Set of 3 Assorted Kitchen Towels",
  "Cast Aluminium Roaster",
  "Super Soft Quick Dry Pedestal Mat",
  "Pure Cotton Striped Pedestal Mat",
  "Chenille Triangle Eyelet Curtains",
  "Super Soft Quick Dry Square Bath Mat",
  "Duck Feather & Down Medium Pillow",
  "Madeline Pure Cotton Floral Bedding Set",
  "Fleece Checked Throw",
  "Woodland Print Embroidered Cushion",
  "12 Piece Tribeca Matte Dinner Set",
  "Tri Ply 18cm Small Saucepan",
  "Cotton Mix Geometric Bedding Set",
  "Henley Pure Wool Rug",
  "Egyptian Cotton Luxury Pedestal Mat",
  "Maisie Floral Embroidered Cushion",
  "Margo Sausage Dog Embroidered Cushion",
  "Geometric Chenille Cushion",
  "Cotton Bamboo Pedestal Mat",
  "Ceramic 32cm Medium Roaster",
  "Chenille Spotted Cushion",
  "Red Christmas Tree Skirt",
  "Fleece Checked Bedding Set",
  "Design & Draw Monsters Activity Kit",
  "Harry Potter™ Ultimate Movie Quiz Game",
  "Felt Stocking Advent Calendar",
  "Harry Potter™ Stocking",
  "Pure Cotton Striped Tassle Cushion",
  "Geometric Chenille Cushion",
  "How to Draw Animals Activity Kit",
  "Cast Aluminium 5L Casserole",
  "Chenille Cushion",
  "Small Hot Water Bottle",
  "Porto 4 Wheel Hard Shell Large Suitcase",
  "Scorpio 4 Wheel Hard Shell Large Suitcase",
  "Two Tone 4 Wheel Large Suitcase",
  "Edith Bedding Set",
  "Pure Cotton Striped Seersucker Bedding Set",
  "Pure Cotton Textured Bedding Set",
  "Waffle Throw",
  "Large Glass Fridge Storage Container",
  "Set of 3 Assorted Kitchen Towels",
  "Set of 3 Assorted Kitchen Towels",
  "Faux Mohair Throw",
  "Bobble Quick Dry Extra Large Bath Mat"
]

def identify_category(name):
    for map_item in maps:
        if map_item['keyword'] in name.lower():
            return map_item['category']


if __name__ == '__main__':
    for name in names:
        category = identify_category(name)
        print(category)


